In [16]:
import pandas as pd
data_2022 = pd.read_csv("./data/데이터_2022.csv")
data_2023 = pd.read_csv("./data/데이터_2023.csv")
df_filtered = data_2022[data_2022['COAW_FLAG_NM'] != '참가증']
data_2023['COAW_FLAG_NM'].value_counts()

COAW_FLAG_NM
3.000000    5069
2.000000    2941
1.000000    1275
2.408616       1
Name: count, dtype: int64

In [17]:
data_2022 = data_2022[data_2022['COAW_FLAG_NM'] != '참가증']
data_2022['COAW_FLAG_NM'].replace({'3등급': 3, '2등급': 2, '1등급': 1}, inplace=True)
data_2022['SEXDSTN_FLAG_CD'].replace({'M': 1, 'F': 0}, inplace=True)
data_2022['AGE_FLAG_NM'].replace({'노인': 4, '성인': 3, '청소년': 2, '유소년': 1}, inplace=True)
data_2022.drop(["CNTER_NM", "MESURE_PLACE_FLAG_NM"], axis=1, inplace=True)
data_2022

,MESURE_TME,AGE_FLAG_NM,MESURE_AGE_CO,INPT_FLAG_NM,COAW_FLAG_NM,MESURE_DAY,SEXDSTN_FLAG_CD,HEIGHT,WEIGHT,BODY_FAT_PERCENTAGE,LOWEST_EAR_PRESSURE,MAX_SYSTOLIC_BLOOD_PRESSURE,GRIP_LEFT,GRIP_RIGHT,SITDOWN_ROLLUP_UPPER,BMI,STANDING_LONG_JUMP,RELATIVE_GRIP
2,4,3,63,관리자,1,20220302,1,182.9,77.60,18.1,77.0,118.0,47.5,47.1,19.7,23.2,184.0,61.2
3,6,3,41,인바디,2,20220302,1,175.0,87.20,29.7,80.0,145.0,46.8,55.0,18.0,28.5,210.0,63.1
4,3,3,64,측정기기,3,20220302,1,176.5,74.80,23.9,81.0,141.0,33.1,39.4,2.8,24.0,NaN,52.7
5,1,3,61,관리자,3,20220302,0,159.0,58.10,40.1,89.0,116.0,24.4,25.0,12.1,23.0,123.0,43.0
6,5,3,30,인바디,1,20220302,1,175.1,76.32,18.3,84.0,124.0,42.3,48.7,17.4,24.9,220.0,63.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15582,2,2,15,관리자,3,20220331,1,166.7,69.40,26.8,88.0,137.0,37.1,32.5,12.1,25.0,168.0,53.5
15585,1,2,13,관리자,3,20220331,1,170.5,52.00,10.5,62.0,146.0,26.1,30.8,2.6,17.9,215.0,59.2
15587,1,2,13,관리자,3,20220331,1,177.0,59.00,14.9,71.0,131.0,28.8,35.6,12.0,18.8,190.0,60.3
15589,1,2,15,관리자,2,20220331,1,189.5,85.70,21.0,91.0,154.0,46.1,49.0,25.6,23.9,210.0,57.2
15591,1,2,15,관리자,2,20220331,1,160.5,45.60,11.9,61.0,105.0,27.7,27.2,8.0,17.7,199.0,60.7

In [18]:
data_2022.keys()

Index(['MESURE_TME', 'AGE_FLAG_NM', 'MESURE_AGE_CO', 'INPT_FLAG_NM',
       'COAW_FLAG_NM', 'MESURE_DAY', 'SEXDSTN_FLAG_CD', 'HEIGHT', 'WEIGHT',
       'BODY_FAT_PERCENTAGE', 'LOWEST_EAR_PRESSURE',
       'MAX_SYSTOLIC_BLOOD_PRESSURE', 'GRIP_LEFT', 'GRIP_RIGHT',
       'SITDOWN_ROLLUP_UPPER', 'BMI', 'STANDING_LONG_JUMP', 'RELATIVE_GRIP'],
      dtype='object')

In [19]:
data_2022["STANDING_LONG_JUMP"].fillna(data_2022["STANDING_LONG_JUMP"].mean())
data_2022 = pd.get_dummies(data_2022)

In [20]:
for key in data_2022.keys():
    data_2022[key].fillna(data_2022[key].mean(), inplace=True)

In [21]:
data_2022.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5651 entries, 2 to 15591
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   MESURE_TME                   5651 non-null   int64
 1   AGE_FLAG_NM                  5651 non-null   int64
 2   MESURE_AGE_CO                5651 non-null   int64
 3   COAW_FLAG_NM                 5651 non-null   int64
 4   MESURE_DAY                   5651 non-null   int64
 5   SEXDSTN_FLAG_CD              5651 non-null   int64
 6   HEIGHT                       5651 non-null   float64
 7   WEIGHT                       5651 non-null   float64
 8   BODY_FAT_PERCENTAGE          5651 non-null   float64
 9   LOWEST_EAR_PRESSURE          5651 non-null   float64
 10  MAX_SYSTOLIC_BLOOD_PRESSURE  5651 non-null   float64
 11  GRIP_LEFT                    5651 non-null   float64
 12  GRIP_RIGHT                   5651 non-null   float64
 13  SITDOWN_ROLLUP_UPPER         5651 non-null   float64
 14  BMI                          5651 non-null   float64
 15  STANDING_LONG_JUMP           5651 non-null   float64
 16  RELATIVE_GRIP                5651 non-null   float64
 17  INPT_FLAG_NM_관리자             5651 non-null   bool
 18  INPT_FLAG_NM_인바디             5651 non-null   bool
 19  INPT_FLAG_NM_측정기기            5651 non-null   bool
dtypes: bool(3), float64(11), int64(6)
memory usage: 811.2 KB

In [22]:
data_2023.to_csv("test.csv")